# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0 # Use the latest Ruff release tag
    hooks:
      - id: ruff
        args: [--unsafe-fixes, --fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.4.0 # Use the latest Black release tag
    hooks:
      - id: black
