[project]
name = "markit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.52.2",
    "fastexcel>=0.14.0",
    "polars>=1.30.0",
    "requests>=2.32.3",
    "typer>=0.16.0",
    "openai>=1.86.0",
]
